### ISSUE TITLE
Instructions - how to use the app

### ISSUE THREAD

**Issue by Artaud** [urbandroid-team/SleepAsFitbit#4]
App should indicate that sleep tracking needs to be started in the phone app, when it's not yet connected

**Comment by JoelBalmer** [comment]
I presume this is text that is displayed on opening the app? then once ready to connect/found a connection, switches to the tracking screen? I could repurpose the welcome screen from my previous PR, it would do the job nicely, although I'd tweak so that when you tap 'go' the button could change text to 'connecting...' and then remove the screen once there's a connection.

Do you have text that you'd like to display? Here's a starting point (repurposed from before):

> Welcome!
Press to start sleep tracking in the phone app, then when that's up and running, return here and tap 'Go' below.
Go

**Comment by Artaud** [comment]
I think that's cool! I would just leave out the need to actually tap that button, and would go straight to "connecting".
The watch app can be in the connecting state for an indefinite period of time, and whenever you start tracking on the phone, it will connect, so there's no need to sync those two things by a button press.

**Comment by Artaud** [comment]
Apparently the instruction text will be needed more than I thought - I tried to publish the app to the Fitbit Gallery and the reviewers returned it because they were unable to find out how it should work.
Thanks @JoelBalmer for getting this on.
